spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bodyguard?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  data:
    mongodb:
      host: 139.196.229.158
      port: 27017
      database: gprs
      username: root
      password: HZjiawawulian@163
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0

mybatis:
  type-aliases-package: com.wanghj.test.domain
  mapper-locations: classpath:mapper/*.xml